---
- name: Install Gpg
  apt:
    name: gnupg
    state: present

- name: Add Postgresql apt repository key.
  apt_key:
    url: "https://www.pgadmin.org/static/packages_pgadmixn_org.pub"
    state: present

- name: Add Postgresql apt repository.
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - '{{ postgresql_repo_url }}'

- name: Install PostgreSQL on Ubuntu
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop:
    - '{{ debian_package }}'

- name: Start postgresql
  service:
    name: postgresql
    state: started
    enabled: true

- name: Congfigure Postgresql
  template:
    src: ubuntu_postgresql.j2
    dest: /etc/postgresql/{{ version }}/main/postgresql.conf

- name: Restart postgresql
  service:
    name: postgresql
    state: restarted
